events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:3001;
    }

    upstream order_service {
        server order-service:3002;
    }

    server {
        listen 80;

        location /data {
            proxy_pass http://user_service/data;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /fetch {
            proxy_pass http://order_service/fetch;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 '{"message": "NGINX работает! Используй /data или /fetch"}';
            add_header Content-Type application/json;
        }
    }
}